#!/usr/bin/env python
import os

libname = "open_desktop_pet_windows"

godot_cpp_dir = os.path.abspath(
    ARGUMENTS.pop(
        "godot_cpp_dir",
        os.path.join("..", "..", "build", "native-deps", "godot-cpp"),
    )
)

local_env = Environment(tools=["default"], PLATFORM="")
local_env["build_profile"] = os.path.abspath("build_profile.json")
opts = Variables([], ARGUMENTS)
opts.Update(local_env)
env = local_env.Clone()

if not os.path.isdir(godot_cpp_dir):
    raise RuntimeError("godot-cpp was not found at: {}".format(godot_cpp_dir))

env = SConscript(
    os.path.join(godot_cpp_dir, "SConstruct"),
    {"env": env, "customs": []},
)
env.Append(CPPPATH=["src"])
env.Append(LIBS=["user32"])

sources = Glob("src/*.cpp")
suffix = env["suffix"].replace(".dev", "").replace(".universal", "")
library = env.SharedLibrary(
    "bin/{}{}{}{}".format(
        env.subst("$SHLIBPREFIX"),
        libname,
        suffix,
        env.subst("$SHLIBSUFFIX"),
    ),
    source=sources,
)

Default(library)
